# Default configuration for C2 prioritization and recommendations

asset_speed_mps: 25.0  # (for intent estimation) If speed exceeds this, intent score (speed-based) converges to 1.0

weights:
  intent: 0.65        # Behavior/speed-based intent
  proximity: 0.35     # TTI normalization (higher when shorter)
  recent: 0.25        # Tracker confidence (includes time decay)
  geo_bonus: 0.20     # Bonus when inside geofence (absolute addition)

thresholds:
  # Score-based decision thresholds (rule C)
  IMMEDIATE_score: 0.80
  SUSPECT_score: 0.60
  # Backward compatibility (if present): IMMEDIATE, SUSPECT

# Multi-condition IMMEDIATE rules (A/B)
immediate_rules:
  tti_ref_sec: 20.0     # Normalization reference for proximity
  tti_sec_hard: 12.0    # (A) Strict TTI threshold
  tti_sec_geofence: 18.0  # (B) Relaxed TTI threshold when inside geofence
  intent_min: 0.75      # (A) Minimum intent threshold
  conf_min: 0.60        # (A) Minimum confidence threshold

# Protected asset (policy anchor) — fall back to target if absent
assets:
  protected_lat: 52.5200
  protected_lon: 13.4050
  geofence_radius_m: 75.0

# Default target (UI/pipeline may pass this value)
target:
  lat: 52.5200
  lon: 13.4050

policy:
  recommend_min_status: SUSPECT     # Use IMMEDIATE only if you want IMMEDIATE cases exclusively
  suspect_monitor_window_sec: 30.0  # Recommended observation window when in SUSPECT state

c2:
  demo_mode: true           # UI/logic may show “SIMULATION ONLY” badge, etc.
  promote_after_sec: 10.0   # (optional) Time-based promotion if used
  require_new_event: false  # Prefer “immediate on first sight” for demo smoothness
  # (optional) auxiliary promotion conditions
  # promote_if_distance_below_m: 150.0
  # promote_if_tti_below_s: 30.0
  # emit_observe_for_suspect: true