# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salute.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'salute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csalute.proto\x12\x04wire\"\x81\x01\n\nSalutePing\x12\x0b\n\x03uid\x18\x01 \x01(\x06\x12\r\n\x05ts_ns\x18\x02 \x01(\x06\x12\r\n\x05lat_q\x18\x03 \x01(\x0f\x12\r\n\x05lon_q\x18\x04 \x01(\x0f\x12\x12\n\ngeo_conf_m\x18\x05 \x01(\x07\x12\x12\n\nevent_code\x18\x06 \x01(\r\x12\x11\n\thash_pref\x18\x07 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'salute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALUTEPING']._serialized_start=23
  _globals['_SALUTEPING']._serialized_end=152
# @@protoc_insertion_point(module_scope)
